"""created_indexes_on_Reviews.userid_and_Reviews.bookid

Revision ID: db5291324dba
Revises: d9d001e70a82
Create Date: 2026-08-15 16:56:01.789779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5291324dba'
down_revision: Union[str, Sequence[str], None] = 'd9d001e70a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Reviews_book_id'), 'Reviews', ['book_id'], unique=False)
    op.create_index(op.f('ix_Reviews_user_id'), 'Reviews', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_book_review', 'Reviews', ['user_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_book_review', 'Reviews', type_='unique')
    op.drop_index(op.f('ix_Reviews_user_id'), table_name='Reviews')
    op.drop_index(op.f('ix_Reviews_book_id'), table_name='Reviews')
    # ### end Alembic commands ###
